spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://106.14.202.122:3306/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 106.14.202.122:8848
  application:
    name: gulimall-member
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000